*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ /DMO/FLIGHT_TRAVEL_CALC_PRICE

    IMPORTING
       REFERENCE(IT_FLIGHT) TYPE !/DMO/IF_FLIGHT_LEGACY=>TT_FLIGHT
           OPTIONAL.