*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ /DMO/FLIGHT_TRAVEL_DELETE

    IMPORTING
       REFERENCE(IV_TRAVEL_ID) TYPE !/DMO/TRAVEL_ID
    EXPORTING
       REFERENCE(ET_MESSAGES) TYPE !/DMO/IF_FLIGHT_LEGACY=>TT_MESSAGE.